export const NAV_LINKS = [
  { label: "Home", href: "/" },
  {
    label: "Digital Resources",
    href: "/resources",
    mega: true,
    children: [
      { label: "eBooks", href: "/resources/ebooks", icon: "BookOpen" },
      { label: "Journals", href: "/resources/journals", icon: "BookMarked" },
      { label: "Research Papers", href: "/resources/research", icon: "FileText" },
      { label: "Thesis Repository", href: "/resources/thesis", icon: "GraduationCap" },
      { label: "Question Papers", href: "/resources/question-papers", icon: "ClipboardList" },
      { label: "Magazines", href: "/resources/magazines", icon: "Newspaper" },
      { label: "Dissertations", href: "/resources/dissertations", icon: "Scroll" },
      { label: "Govt Publications", href: "/resources/govt", icon: "Building2" },
      { label: "Reports", href: "/resources/reports", icon: "BarChart3" },
    ],
  },
  {
    label: "Departments",
    href: "/departments",
    children: [
      { label: "Engineering", href: "/departments/engineering" },
      { label: "Science", href: "/departments/science" },
      { label: "Commerce", href: "/departments/commerce" },
      { label: "Management", href: "/departments/management" },
      { label: "Arts & Humanities", href: "/departments/arts" },
      { label: "Law", href: "/departments/law" },
      { label: "Medical Sciences", href: "/departments/medical" },
      { label: "Computer Science", href: "/departments/cs" },
    ],
  },
  { label: "Library Services", href: "/services" },
  { label: "Announcements", href: "/announcements" },
  { label: "Downloads", href: "/downloads" },
  { label: "Contact", href: "/contact" },
];

export const STATS = [
  { value: 2500000, suffix: "+", label: "Books", icon: "BookOpen" },
  { value: 180000, suffix: "+", label: "Research Papers", icon: "FileText" },
  { value: 85000, suffix: "+", label: "eBooks", icon: "Tablet" },
  { value: 125000, suffix: "+", label: "Students", icon: "Users" },
  { value: 8500, suffix: "+", label: "Teachers", icon: "GraduationCap" },
  { value: 42, suffix: "", label: "Departments", icon: "Building2" },
  { value: 9500000, suffix: "+", label: "Downloads", icon: "Download" },
  { value: 18000, suffix: "+", label: "Daily Visitors", icon: "TrendingUp" },
];

export const RESOURCES = [
  {
    id: 1,
    title: "Books",
    description: "Access over 2.5 million physical and digital books across all disciplines.",
    count: "2,500,000+",
    icon: "BookOpen",
    color: "from-navy to-gov-blue",
    bg: "bg-blue-50 dark:bg-blue-950/20",
    iconColor: "text-gov-blue",
  },
  {
    id: 2,
    title: "eBooks",
    description: "Instantly access our full collection of digital books on any device, anywhere.",
    count: "85,000+",
    icon: "Tablet",
    color: "from-gov-blue to-cyan-600",
    bg: "bg-cyan-50 dark:bg-cyan-950/20",
    iconColor: "text-cyan-600",
  },
  {
    id: 3,
    title: "Research Papers",
    description: "Peer-reviewed research papers from leading journals and institutions.",
    count: "180,000+",
    icon: "FileText",
    color: "from-gov-green to-emerald-600",
    bg: "bg-emerald-50 dark:bg-emerald-950/20",
    iconColor: "text-gov-green",
  },
  {
    id: 4,
    title: "Question Papers",
    description: "Previous year exam papers across all departments and semesters.",
    count: "45,000+",
    icon: "ClipboardList",
    color: "from-saffron to-orange-500",
    bg: "bg-orange-50 dark:bg-orange-950/20",
    iconColor: "text-saffron",
  },
  {
    id: 5,
    title: "Magazines",
    description: "Current and archived issues of academic and general interest magazines.",
    count: "3,200+",
    icon: "Newspaper",
    color: "from-purple-600 to-pink-600",
    bg: "bg-purple-50 dark:bg-purple-950/20",
    iconColor: "text-purple-600",
  },
  {
    id: 6,
    title: "Journals",
    description: "National and international scholarly journals across all fields of study.",
    count: "12,500+",
    icon: "BookMarked",
    color: "from-teal-600 to-gov-blue",
    bg: "bg-teal-50 dark:bg-teal-950/20",
    iconColor: "text-teal-600",
  },
  {
    id: 7,
    title: "Thesis & Dissertations",
    description: "Complete repository of doctoral and masters theses from this institution.",
    count: "28,000+",
    icon: "GraduationCap",
    color: "from-indigo-600 to-navy",
    bg: "bg-indigo-50 dark:bg-indigo-950/20",
    iconColor: "text-indigo-600",
  },
  {
    id: 8,
    title: "Govt Publications",
    description: "Official government reports, gazettes, policy documents, and white papers.",
    count: "95,000+",
    icon: "Building2",
    color: "from-saffron via-white to-gov-green",
    bg: "bg-amber-50 dark:bg-amber-950/20",
    iconColor: "text-amber-600",
  },
  {
    id: 9,
    title: "Reports & Analytics",
    description: "Annual reports, survey data, and institutional research publications.",
    count: "18,000+",
    icon: "BarChart3",
    color: "from-slate-600 to-navy",
    bg: "bg-slate-50 dark:bg-slate-800/20",
    iconColor: "text-slate-600",
  },
  {
    id: 10,
    title: "Newspapers",
    description: "Digital archives of national and regional newspapers from across India.",
    count: "500+",
    icon: "ScrollText",
    color: "from-gray-700 to-slate-800",
    bg: "bg-gray-50 dark:bg-gray-800/20",
    iconColor: "text-gray-600",
  },
  {
    id: 11,
    title: "Audio Books",
    description: "Listen to thousands of books in Hindi, English, and regional languages.",
    count: "8,500+",
    icon: "Headphones",
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-50 dark:bg-rose-950/20",
    iconColor: "text-rose-500",
  },
  {
    id: 12,
    title: "Video Lectures",
    description: "Recorded lectures from distinguished faculty and expert guest speakers.",
    count: "22,000+",
    icon: "Video",
    color: "from-violet-600 to-purple-700",
    bg: "bg-violet-50 dark:bg-violet-950/20",
    iconColor: "text-violet-600",
  },
];

export const SERVICES = [
  { title: "Book Search", desc: "Find any book in seconds", icon: "Search" },
  { title: "Online Reading", desc: "Read directly in browser", icon: "BookOpen" },
  { title: "Digital Membership", desc: "Instant online access", icon: "CreditCard" },
  { title: "Research Support", desc: "Expert research guidance", icon: "FlaskConical" },
  { title: "Book Reservation", desc: "Reserve before you visit", icon: "Calendar" },
  { title: "Renew Membership", desc: "Quick online renewal", icon: "RefreshCw" },
  { title: "Reference Services", desc: "Ask a librarian", icon: "MessageSquare" },
  { title: "Subject Resources", desc: "Curated by department", icon: "FolderOpen" },
  { title: "Library Notices", desc: "Stay updated always", icon: "Bell" },
  { title: "Reading History", desc: "Track your progress", icon: "History" },
];

export const DEPARTMENTS = [
  { name: "Engineering", books: "124,500", faculty: 142, icon: "Cpu", color: "#005BAC" },
  { name: "Science", books: "98,300", faculty: 118, icon: "FlaskConical", color: "#138808" },
  { name: "Commerce", books: "67,200", faculty: 86, icon: "TrendingUp", color: "#FF9933" },
  { name: "Management", books: "54,800", faculty: 74, icon: "Briefcase", color: "#7C3AED" },
  { name: "Arts & Humanities", books: "82,100", faculty: 96, icon: "Palette", color: "#DB2777" },
  { name: "Law", books: "41,500", faculty: 52, icon: "Scale", color: "#003366" },
  { name: "Agriculture", books: "38,700", faculty: 64, icon: "Leaf", color: "#059669" },
  { name: "Medical Sciences", books: "76,400", faculty: 108, icon: "Stethoscope", color: "#DC2626" },
  { name: "Computer Science", books: "89,600", faculty: 124, icon: "Monitor", color: "#0891B2" },
  { name: "Social Sciences", books: "61,200", faculty: 78, icon: "Globe", color: "#D97706" },
];

export const ANNOUNCEMENTS = [
  {
    day: "28",
    month: "Jul",
    tag: "Notice",
    tagType: "notice",
    title: "Library Timings Extended for Semester Examinations 2025",
    meta: "Library Administration • 2 hours ago",
  },
  {
    day: "25",
    month: "Jul",
    tag: "Event",
    tagType: "event",
    title: "National Seminar on Digital Learning Resources — August 5–6, 2025",
    meta: "Academic Affairs • 3 days ago",
  },
  {
    day: "22",
    month: "Jul",
    tag: "Alert",
    tagType: "alert",
    title: "Scheduled System Maintenance on July 30, 2025 (02:00–06:00 AM)",
    meta: "IT Department • 6 days ago",
  },
  {
    day: "18",
    month: "Jul",
    tag: "Notice",
    tagType: "notice",
    title: "New Batch of Research Journals Added — IEEE, Elsevier, Springer",
    meta: "Content Team • 10 days ago",
  },
  {
    day: "15",
    month: "Jul",
    tag: "Event",
    tagType: "event",
    title: "Workshop: Citation Management with Zotero & Mendeley — August 2",
    meta: "Research Support Cell • 13 days ago",
  },
  {
    day: "10",
    month: "Jul",
    tag: "Notice",
    tagType: "notice",
    title: "Holiday: Library Closed on Independence Day — August 15, 2025",
    meta: "Library Administration • 18 days ago",
  },
];

export const DOWNLOADS = [
  { name: "Library Rules & Regulations", size: "1.2 MB", type: "PDF", tag: "Updated" },
  { name: "Membership Application Form", size: "486 KB", type: "PDF", tag: "New" },
  { name: "User Manual — Digital Portal", size: "3.8 MB", type: "PDF", tag: "" },
  { name: "Research Guidelines 2025", size: "2.1 MB", type: "PDF", tag: "Updated" },
  { name: "Privacy & Data Policy", size: "890 KB", type: "PDF", tag: "" },
  { name: "Annual Report 2024–25", size: "8.4 MB", type: "PDF", tag: "New" },
];

export const WHY_CHOOSE = [
  { title: "Secure Platform", desc: "Bank-grade encryption and HTTPS-secured access to all digital resources.", icon: "ShieldCheck" },
  { title: "24×7 Access", desc: "Access the entire digital collection anytime, from anywhere in the world.", icon: "Clock" },
  { title: "Verified Resources", desc: "All content is vetted, peer-reviewed, and authenticated by domain experts.", icon: "BadgeCheck" },
  { title: "Government Approved", desc: "Compliant with Ministry of Education guidelines and UGC recommendations.", icon: "Building2" },
  { title: "Mobile Friendly", desc: "Fully responsive portal and dedicated apps for Android and iOS devices.", icon: "Smartphone" },
  { title: "Fast Search", desc: "AI-powered search delivers accurate results across millions of documents instantly.", icon: "Zap" },
  { title: "Multi-language", desc: "Available in Hindi, English, and 12 regional Indian languages.", icon: "Globe" },
  { title: "Digital Archive", desc: "Permanent digital preservation of rare manuscripts and historical documents.", icon: "Archive" },
];

export const TESTIMONIALS = [
  {
    quote: "The Digital Library Portal has completely transformed how I conduct my research. Access to thousands of journals from my hostel room is something I could only dream of before.",
    name: "Priya Sharma",
    role: "PhD Scholar, Computer Science",
    initials: "PS",
    color: "#005BAC",
    stars: 5,
  },
  {
    quote: "As a faculty member, I recommend the portal to all my students. The quality of resources, especially the thesis repository and government publications, is unmatched.",
    name: "Dr. Rajesh Kumar",
    role: "Associate Professor, Engineering",
    initials: "RK",
    color: "#138808",
    stars: 5,
  },
  {
    quote: "The 24x7 availability has been a game-changer for me. I can access study material at midnight before exams without worrying about library hours.",
    name: "Arjun Nair",
    role: "Final Year Student, Law",
    initials: "AN",
    color: "#FF9933",
    stars: 5,
  },
  {
    quote: "Managing the library's digital assets has never been easier. The admin dashboard gives us complete visibility into usage patterns and resource gaps.",
    name: "Ms. Sunita Mehta",
    role: "Chief Librarian",
    initials: "SM",
    color: "#7C3AED",
    stars: 5,
  },
  {
    quote: "From citation management to reference support, the research assistance features have directly improved the quality and speed of my academic work.",
    name: "Dr. Anika Patel",
    role: "Researcher, Life Sciences",
    initials: "AP",
    color: "#DB2777",
    stars: 5,
  },
  {
    quote: "The multi-language support is outstanding. Being able to access resources in Tamil and Hindi alongside English makes this truly inclusive.",
    name: "Vikram Rajan",
    role: "Postgraduate Student, Commerce",
    initials: "VR",
    color: "#0891B2",
    stars: 5,
  },
];

export const FEATURED_BOOKS = [
  { title: "Advanced Algorithms & Data Structures", author: "Cormen, Leiserson et al.", dept: "CS", badge: "Trending", color: "from-blue-800 to-blue-600" },
  { title: "Constitutional Law of India", author: "Dr. J.N. Pandey", dept: "Law", badge: "Faculty Pick", color: "from-navy to-gov-blue" },
  { title: "Organic Chemistry", author: "Morrison & Boyd", dept: "Science", badge: "Most Read", color: "from-green-800 to-gov-green" },
  { title: "Principles of Management", author: "Koontz & Weihrich", dept: "Mgmt", badge: "New", color: "from-purple-800 to-indigo-600" },
  { title: "Engineering Mathematics Vol. II", author: "Dr. B.S. Grewal", dept: "Engg", badge: "Trending", color: "from-slate-700 to-slate-500" },
  { title: "Indian Economic Policy", author: "Dutt & Sundharam", dept: "Commerce", badge: "Faculty Pick", color: "from-amber-700 to-saffron" },
];

export const TICKER_ITEMS = [
  "New: 5,000+ IEEE journals added to the collection",
  "Workshop on Research Methodology — Register by August 1",
  "Extended library hours during semester exams: 7 AM to 11 PM",
  "Mobile app v3.0 now available on Google Play and App Store",
  "New: Digital archive of rare manuscripts now accessible",
  "Upcoming: National Book Fair — August 20–25, 2025",
  "Maintenance: Portal will be briefly unavailable July 30, 02:00–06:00 AM",
];
